apiVersion: v1
kind: Pod
metadata:
  name: clustershell
  labels:
    app: clustershell
spec:
  containers:
  - name: clustershell
    image: ubuntu:latest
    command: ["sh", "-c", "sleep 10000"]
    imagePullPolicy: IfNotPresent