apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-deployment
  namespace: iot
  labels:
    app: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: ha-config
          hostPath:
            path: /mnt/zfs-nas/cluster/home-assistant/config
            type: Directory
      containers:
        - name: homeassistant
          image: docker.io/homeassistant/home-assistant:2022.4
          volumeMounts:
            - mountPath: /config
              name: ha-config
          ports:
            - containerPort: 8123
              name: www
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: iot
  labels:
    app: homeassistant
  annotations:
    metallb.universe.tf/address-pool: external-ip-pool
spec:
  selector:
    app: homeassistant
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.26
  ports:
    - name: ha-www
      protocol: TCP
      port: 80
      targetPort: 8123
