# consider implementing:
# https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#examples
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapserver-deployment
  namespace: iot
  labels:
    app: snapserver
spec:
  selector:
    matchLabels:
      app: snapserver
  replicas: 1
  template:
    metadata:
      labels:
        app: snapserver
    spec:
      nodeSelector:
        arch: aarch64
      containers:
        - name: snapserver
          image: docker.io/atticuss/snapcast-server:aarch64
          imagePullPolicy: Always
          ports:
            - containerPort: 1704
              name: snap-server
              protocol: TCP
            - containerPort: 1705
              name: snap-control
              protocol: TCP
            - containerPort: 1780
              name: snap-web
              protocol: TCP
            - containerPort: 1704
              name: snap-server-udp
              protocol: UDP
            - containerPort: 1705
              name: snap-ctrl-udp
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: snapserver-tcp
  namespace: iot
  labels:
    app: snapserver
  annotations:
    metallb.universe.tf/address-pool: external-ip-pool
    metallb.universe.tf/allow-shared-ip: snapserver-svc
spec:
  selector:
    app: snapserver
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.25
  ports:
    - name: snap-server
      protocol: TCP
      port: 1704
      targetPort: 1704
    - name: snap-control
      protocol: TCP
      port: 1705
      targetPort: 1705
    - name: snap-web
      protocol: TCP
      port: 1780
      targetPort: 1780
---
apiVersion: v1
kind: Service
metadata:
  name: snapserver-udp
  namespace: iot
  labels:
    app: snapserver
  annotations:
    metallb.universe.tf/address-pool: external-ip-pool
    metallb.universe.tf/allow-shared-ip: snapserver-svc
spec:
  selector:
    app: snapserver
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.25
  ports:
    - name: snap-server-udp
      protocol: UDP
      port: 1704
      targetPort: 1704
    - name: snap-ctrl-udp
      protocol: UDP
      port: 1705
      targetPort: 1705
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: snapclient-daemon
  namespace: iot
  labels:
    app: snapclient
spec:
  selector:
    matchLabels:
      app: snapclient
  template:
    metadata:
      labels:
        app: snapclient
    spec:
      nodeSelector:
        type: audio
      containers:
        - name: snapclient
          image: docker.io/atticuss/snapcast-client:aarch64
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /dev/snd
              name: dev-snd
          env:
            - name: "SNAPSERVER"
              value: "192.168.1.25"
          # used to allow access to /dev/snd
          securityContext:
            privileged: true
      volumes:
        - name: dev-snd
          hostPath:
            path: /dev/snd
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "audio"
          effect: "NoSchedule"
