apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrape
  labels:
    app: scrape
  namespace: data-harvest
spec:
  selector:
    matchLabels:
      app: scrape
  replicas: 1
  template:
    metadata:
      labels:
        app: scrape
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://192.168.1.111:8200"
        vault.security.banzaicloud.io/vault-role: "vault-injector"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      volumes:
      - name: cb-data
        hostPath:
          path: /mnt/gfs/cluster/exchange_data/coinbase
          type: Directory
      - name: reddit-data
        hostPath:
          path: /mnt/gfs/cluster/sentiment_data/reddit
          type: Directory
      containers:
      - name: ex-scrape
        image: docker.io/atticuss/exchange_scrape:coinbase
        imagePullPolicy: IfNotPresent
        tty: True # required to reliably get print() statements from "kubectl logs"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: API_PASS
          value: vault:kv/data/coinbase#API_PASS
        - name: API_SECRET
          value: vault:kv/data/coinbase#API_SECRET
        - name: API_KEY
          value: vault:kv/data/coinbase#API_KEY
        volumeMounts:
        - mountPath: /data
          name: cb-data
      - name: sent-scrape
        image: docker.io/atticuss/sentiment_scrape:reddit
        imagePullPolicy: IfNotPresent
        tty: True # required to reliably get print() statements from "kubectl logs"
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        volumeMounts:
        - mountPath: /data
          name: reddit-data
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.1.80
          - 192.168.1.1
