apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  replicas: 1
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      volumes:
      - name: tutorial-logs
        hostPath:
          path: /mnt/gvolume0/cluster/logstash_tut/logstash_tutorial.log
          type: File
      - name: pihole-logs
        hostPath:
          path: /mnt/gvolume0/cluster/pihole/pihole.log
          type: File
      - name: filebeat-config
        configMap:
          name: filebeat-configmap
      containers:
      - name: filebeat
        image: docker.io/atticuss/filebeat:6.6-aarch64
        volumeMounts:
        - mountPath: /var/log/pihole.log
          name: pihole-logs
        - mountPath: /etc/filebeat/filebeat.yml
          name: filebeat-config
          subPath: filebeat.yml