kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      name: traefik
  template:
    metadata:
      labels:
        app: traefik
        name: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.6
          args:
            - --log.level=DEBUG
            - --api
            - --api.insecure
            - --entrypoints.web.address=:80
            - --entrypoints.dgraph.address=:9080
            - --entrypoints.altweb.address=:8000
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080
            - name: dgraph
              containerPort: 9080
            - name: altweb
              containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
    - protocol: TCP
      port: 8080
      name: admin
      targetPort: 8080
    - protocol: TCP
      port: 9080
      name: dgraph
      targetPort: 9080
    - protocol: TCP
      port: 8000
      name: altweb
      targetPort: 8000