# helm install graylog kongz/graylog --version 2.1.1 --namespace graylog \
# --set graylog.persistence.storageClass="graylog-pv" \
# --set graylog.persistence.size="20Gi" \
# --set graylog.replicas="1" \
# --set mongodb.global.storageClass="mongodb-pv" \
# --set mongodb.persistence.size="10Gi" \
# --set mongodb.architecture="standalone" \
# --set elasticsearch.volumeClaimTemplate.storageClassName="elasticsearch-pv" \
# --set elasticsearch.volumeClaimTemplate.resources.requests.storage="20Gi" \
# --set elasticsearch.replicas="1" \
# --debug
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graylog
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: graylog
  source:
    chart: graylog
    repoURL: https://charts.kong-z.com
    targetRevision: 2.1.1
    #repoURL: https://github.com/KongZ/charts
    #targetRevision: graylog-4.2
    #path: charts/graylog
    helm:
      parameters:
        # https://github.com/bitnami/charts/tree/master/bitnami/mongodb/#parameters
        - name: mongodb.global.storageClass
          value: mongodb-pv
        - name: mongodb.persistence.size
          value: 10Gi
        - name: mongodb.architecture
          value: standalone
        # https://github.com/elastic/helm-charts/blob/main/elasticsearch/README.md#configuration
        - name: elasticsearch.volumeClaimTemplate.storageClassName
          value: elasticsearch-pv
        - name: elasticsearch.volumeClaimTemplate.resources.requests.storage
          value: 20Gi
        - name: elasticsearch.replicas
          value: "1"
        # https://artifacthub.io/packages/helm/kong-z/graylog#configuration
        - name: graylog.persistence.storageClass
          value: graylog-pv
        - name: graylog.persistence.size
          value: 20Gi
        - name: graylog.replicas
          value: "1"
        - name: graylog.input.tcp.service.annotations
          value: "metallb.universe.tf/address-pool: external-ip-pool
            metallb.universe.tf/allow-shared-ip: pihole-svc"
        - name: graylog.input.udp.service.annotations
          value: "metallb.universe.tf/address-pool: external-ip-pool
            metallb.universe.tf/allow-shared-ip: pihole-svc"
        - name: graylog.input
          value: "tcp:
              service:
                type: LoadBalancer
                externalTrafficPolicy: Local
                loadBalancerIP: 192.168.1.27
              ports:
                - name: gelf1
                  port: 12222
                - name: gelf2
                  port: 12223"
        #    udp:
        #      service:
        #        type: LoadBalancer
        #        externalTrafficPolicy: Local
        #        loadBalancerIP: 192.168.1.27
        #      ports:
        #        - name: syslog
        #          port: 5410"