apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      # bit o' anti-affinity to force pods to be distributed across nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - elasticsearch
              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: es-data
        hostPath:
          path: /mnt/gvolume0/cluster/elasticsearch
          type: Directory
      - name: es-config
        configMap:
          name: es-configmap
      initContainers:
      # NOTE:
      # This is to fix the permission on the volume
      # By default elasticsearch container is not run as non root user.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: fix-es-data-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /data
        securityContext:
          privileged: true
        volumeMounts:
        - name: es-data
          mountPath: /data
      # NOTE:
      # To increase the default vm.max_map_count to 262144
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      # To increase the ulimit
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.io/atticuss/elasticsearch:6.6.2-aarch64
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        env:
        #- name: discovery.type
        #  value: "single-node"
        - name: cluster.name
          value: es-cluster
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: NETWORK_HOST
          value: _site_,_lo_
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: MAX_LOCAL_STORAGE_NODES
          value: "5"
        - name: DISCOVERY_SERVICE
          value: es-discovery
        volumeMounts:
        - mountPath: /data
          name: es-data
        - mountPath: /elasticsearch/config/elasticsearch.yml
          name: es-config
          subPath: elasticsearch.yml
        ports:
        - containerPort: 9200
          name: es-http
          protocol: TCP
        - containerPort: 9300
          name: es-comms
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: es-external-service
  labels:
    app: elasticsearch
  annotations:
    metallb.universe.tf/address-pool: external-ip-pool
    metallb.universe.tf/allow-shared-ip: es-service
spec:
  selector:
    app: elasticsearch
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: es-http
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: es-comms
    protocol: TCP
    port: 9300
    targetPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: es-http
    port: 9200
    protocol: TCP
  - name: es-comms
    port: 9300
    protocol: TCP