apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
  namespace: default
data:
  filebeat.yml: |+
    filebeat.prospectors:
    - type: log
      paths:
        - /var/log/pihole.log 
    output.logstash:
      hosts: ["logstash-discovery.default.svc.cluster.local:5044"]