apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      volumes:
      - name : kibana-config
        configMap:
          name: kibana-configmap
          items:
          - key: kibana.yml
            path: kibana.yml
      - name : logtrail-config
        configMap:
          name: kibana-configmap
          items:
          - key: logtrail.json
            path: logtrail.json
      containers:
      - name: kibana
        image: docker.io/atticuss/kibana:6.6.2-aarch64
        volumeMounts:
        - name: kibana-config
          mountPath: /opt/kibana/config
        - name: logtrail-config
          mountPath: /opt/kibana/plugins/logtrail/logtrail.json
          subPath: logtrail.json
        ports:
        - containerPort: 5601
          name: kibana-web
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  labels:
    app: kibana
  annotations:
    metallb.universe.tf/address-pool: external-ip-pool
spec:
  selector:
    app: kibana
  type: LoadBalancer
  #externalTrafficPolicy: Local
  ports:
  - name: kibana-web
    protocol: TCP
    port: 80
    targetPort: 5601