apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default
data:
  dnsmasq: |
    logdate [\w]{3}\s[\s\d]{2}\s\d\d\:\d\d\:\d\d
    blocklist [\/\w\.]+
    domain [\w\.\-]+
    clientip \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
    ip \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
  pipeline.conf: |
    input {
      beats {
          port => "5044"
          type => "logs"
        }
    }

    filter {
      grok {
        patterns_dir => ["/usr/share/logstash/patterns"]
        match => { 
          "message" => [
            "^%{logdate:LOGDATE} dnsmasq\[[\d]+\]\: query\[[\w]+\] %{domain:DOMAIN} from %{clientip:CLIENTIP}", 
            "^%{logdate:LOGDATE} dnsmasq\[[\d]+\]\: reply %{domain:DOMAIN} is %{ip:IP}", 
            "^%{logdate:LOGDATE} dnsmasq\[[\d]+\]\: %{blocklist:BLOCKLIST} %{domain:DOMAIN} is %{ip:IP}"
          ]
        }
      }

      date {
        match => [ "LOGDATE", "MMM dd HH:mm:ss", "MMM  d HH:mm:ss" ]
      }

      geoip {
        source => "IP"
      }
    }

    output {
      elasticsearch {
        hosts => [ "es-discovery.default.svc.cluster.local:9200" ]
        index => "logstash-dnsmasq-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }