apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
  namespace: secure-dns
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: docker.io/visibilityspots/cloudflared:latest
        ports:
        - containerPort: 5054
          name: cloudflared-dns
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-service
  namespace: secure-dns
  labels:
    app: cloudflared
  annotations:
    metallb.universe.tf/address-pool: external-ip-pool
spec:
  selector:
    app: cloudflared
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  clusterIP: 10.3.238.235
  loadBalancerIP: 192.168.1.21
  ports:
  - name: cloudflared-dns
    protocol: UDP
    port: 53
    targetPort: 5054